/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////


using System;
using System.Collections.Generic;
namespace Fangtang
{
    public class LogTag
    {
        public const int RuntimeFlagInt = -1;
        public const int None = 0;
        public const int PvpEnter = 1;
        public const int PvpRacing = 2;
        public const int PvpEnd = 3;
        public const int GamePlay = 4;
        public const int Pve = 5;
        public const int BeforeLogin = 6;
        public const int Character = 7;
        public const int Vehicle = 8;
        public const int Camera = 9;
        public const int Map = 10;
        public const int Powerup = 11;
        public const int Tutorial = 12;
        public const int UI = 13;
        public const int Http = 14;
        public const int ButtonPath = 15;
        public const int Chat = 16;
        public const int Waypoint = 17;
        public const int HeadIcon = 18;
        public const int Announcement = 19;
        public const int ServerLog = 20;
        public const int LOD = 21;
        public const int Audio = 22;
        public const int Assets = 23;
        public const int Other = 24;
        public const int MapRace = 25;
        public const int Inventory = 26;
        public const int Looting = 27;
        public const int HoloCompound = 28;
        public const int SDK = 29;
        public const int HoloStar = 30;
        public static List<string> _tagStrings;
        static LogTag()
        {
            _tagStrings = new List<string>();
            _tagStrings.Add("None");
            _tagStrings.Add("PvpEnter");
            _tagStrings.Add("PvpRacing");
            _tagStrings.Add("PvpEnd");
            _tagStrings.Add("GamePlay");
            _tagStrings.Add("Pve");
            _tagStrings.Add("BeforeLogin");
            _tagStrings.Add("Character");
            _tagStrings.Add("Vehicle");
            _tagStrings.Add("Camera");
            _tagStrings.Add("Map");
            _tagStrings.Add("Powerup");
            _tagStrings.Add("Tutorial");
            _tagStrings.Add("UI");
            _tagStrings.Add("Http");
            _tagStrings.Add("ButtonPath");
            _tagStrings.Add("Chat");
            _tagStrings.Add("Waypoint");
            _tagStrings.Add("HeadIcon");
            _tagStrings.Add("Announcement");
            _tagStrings.Add("ServerLog");
            _tagStrings.Add("LOD");
            _tagStrings.Add("Audio");
            _tagStrings.Add("Assets");
            _tagStrings.Add("Other");
            _tagStrings.Add("MapRace");
            _tagStrings.Add("Inventory");
            _tagStrings.Add("Looting");
            _tagStrings.Add("HoloCompound");
            _tagStrings.Add("SDK");
            _tagStrings.Add("HoloStar");
        }
        public static string GetTag(int tagInt)
        {
            if (tagInt < _tagStrings.Count)
            {
                return _tagStrings[tagInt];
            }
            return "";
        }
    }
}
